### PR TITLE
Cleaned video data

### PR DESCRIPTION
**Pull request by it-is-wednesday**
;)

### CODE REVIEW

**Review by maxmargolin — APPROVED** [review]
E S T H E T I C

**Comment by it-is-wednesday** [comment]
אנגלית? `)

**Review by maxmargolin — APPROVED** [review]
E S T H E T I C

**Comment by it-is-wednesday** [comment]
Halas approving

**Comment by it-is-wednesday** [comment]
Nice

**Comment by maxmargolin** [comment]
Thanks

**Pull request merged**
